### ISSUE TITLE
Crear un prototipo de la card de una anp

### ISSUE THREAD

**Issue by LisandroEmmanuel** [lasolUndav/anp#5]
-hacer un prototipo a mano o usando mockflow

-ver ejemplos en las cards:
https://waffle.io/duluca/local-weather-app/cards/5a417d6cd10e68001de36544

**Comment by AnaMariaRomero** [comment]
https://wireframepro.mockflow.com/view/M5dc1706aa5ff90e3969734e19ef8fdc41553195004023#/page/e38016643a074b19a200d08cb47d11b3
