### ISSUE TITLE
Crear prototipo de la grilla de la pagina

### ISSUE THREAD

**Issue by LisandroEmmanuel** [lasolUndav/anp#7]

**Comment by AnaMariaRomero** [comment]
https://wireframepro.mockflow.com/view/M5dc1706aa5ff90e3969734e19ef8fdc41553195004023#/page/e38016643a074b19a200d08cb47d11b3

**Comment by lasolUndav** [comment]
Me gusta.  Podemos implementar esto, luego cuando tengamos una reunión con ellos que se encarguen de darnos feedback y seguramente van a querer darnos otras imágenes.
Tambien deberiamos ver que otros datos mostrar.
